<x-layouts.portfolio
    :profile="$profile"
    :colors="$colors"
    :overlay="$overlay"
    :overlayIntensity="$overlayIntensity"
    :sectionsOrder="$sectionsOrder"
    :navbarLinks="$navbarLinks"
    :nowItems="$nowItems"
    :projects="$projects"
    :experiences="$experiences"
    :skills="$skills"
/>
